Repository milharal-dev/nemli-nemlerei-bot, pull requests merged in 2024-07, with the labels that each got.

#16 refactor: Formatting
  nemli/commands/utility/ping.py
  nemli/commands/utility/summarize.py
  nemli/config.py
  nemli/main.py
  pyproject.toml
Labels: refactor, dx

#14 feat: General improvements
  .env.template
  README.md
  nemli/commands/utility/summarize.py
  nemli/config.py
  nemli/main.py
  nemli/nlp/messages.py
  pdm.lock
  pyproject.toml
  tests/test_stopwords.py
Labels: enhancement, refactor

#19 fix: Missing stopwords
  nemli/commands/utility/summarize.py
Labels: bug

#22 chore: Adding code owners to the repo
  .github/CODEOWNERS
Labels: enhancement, dx, chore

#27 chore: Code Owners file fix
  .github/CODEOWNERS
Labels: bug

#21 Multiple discord message support + .ipynb tests
  .gitignore
  nemli/commands/utility/summarize.py
Labels: enhancement

#25 feature: Get last bot message and link it instead of doing a new summary
  .gitignore
  nemli/commands/utility/summarize.py
  nemli/nlp/messages.py
  nemli/schemas/messages.py
  nemli/services/messages.py
  tests/extras/mocks.py
  tests/test_parsed_discord_messages.py
  tests/test_stopwords.py
Labels: enhancement

#24 DX: pre-commit
  .pre-commit-config.yaml
  nemli/commands/utility/summarize.py
  pdm.lock
  pyproject.toml
  tests/conftest.py
  tests/test_stopwords.py
Labels: dx

#37 Adding a link to latest message summarized
  nemli/commands/utility/summarize.py
Labels: enhancement

#35 Message separation by heading and other improvements
  nemli/commands/utility/summarize.py
  tests/test_msg_separarion.py
Labels: enhancement

#38 Parametrize model temperature also small changes to prompt
  .env.template
  nemli/commands/utility/summarize.py
  nemli/config.py
  nemli/services/messages.py
Labels: enhancement

#39 feat: Add the option for the user to select a custom prompt style (fun)
  nemli/commands/utility/summarize.py
  nemli/schemas/prompt_style.py
Labels: enhancement

#42 Refactoring on message separation + Prompt engineering
  nemli/commands/utility/summarize.py
  nemli/config.py
  nemli/schemas/prompt_style.py
  tests/test_msg_separarion.py
Labels: bug, refactor

#46 feat: Added more prompt types
  nemli/schemas/prompt_style.py
Labels: enhancement

#45 feat: Added a exception to handle 403 Forbidden
  nemli/commands/utility/summarize.py
Labels: bug
